### ISSUE TITLE
Help doesn't work on username

### ISSUE THREAD

**Issue by Synchro** [ghost-town/grunt-init-assemble#10]
I wasn't sure what the username field was for (e.g. local or github?), so I gave it a `?`, but it doesn't like that:
![screen shot 2013-12-24 at 11 08 44](https://f.cloud.github.com/assets/81561/1805479/6aa0ef3a-6c83-11e3-8c2c-917465add90b.png)

**Comment by jonschlinkert** [comment]
Should be resolved. Please reopen this if you still have issues
