### ISSUE TITLE
update package.json cause broken dependencies

### ISSUE THREAD

**Issue by torosgo** [ghost-town/grunt-init-assemble#13]
I tried to update npm packages in package.json, but dependencies got broken. 

To reproduce:
- Install npm-check-updates
- In project folder where there is package.json, run: 
  $ npm-check-updates -u
  this updates package.json to latest packages
- Run 'npm update' for the latest packages in package.json to get installed

You will see many warnings about dependencies.

Also after update, if you run "grunt" the process exits while Running "assemble:example" (assemble) task

Is it possible to update dependencies?

Thanks

**Comment by jonschlinkert** [comment]
It's possible, but I'd recommend using the [generator](https://github.com/assemble/generator-assemble) instead. This project will be officially deprecated after we release the next version of assemble.

**Comment by nschonni** [comment]
`npm-check-updates` project doesn't look like it's maintained anymore and looks like it has open bugs for updating the deps too far ahead. I'd suggest https://github.com/alanshaw/david, but I'm not sure if this issue is really with this repo at all.

**Comment by torosgo** [comment]
I tried david too but npm-check-updates  seemed more stable, at least it doesnt update packages, just the package.json with the latest versions (david caused different problems with npm in nvm). 

Anyway I will use generator-assemble.

I don't know if this is the place but I would like to start a discussion about the expected user experience for these generators/boilerplates. In common usage there exists a need for a "personel site plus a blog with some feature set like githubpages, comments ..." Generator-assemble is a base and it is needed, but I think there is also a need for a more feature rich boilerplate like this one that meets the expectations of a more ready to use and extendable pack. 

I know you can make that all by using assemble, but it is about teaching how to fish vs giving a fish ready to be baked. So I believe grunt-init-assemble is a good example and it attracts attention. Maybe also another, more extended yeoman pack would be good.

Or, it would be better if Generator-assemble would do all of these optionally.

Thanks

**Comment by jonschlinkert** [comment]
great feedback! please feel free to add these comments on https://github.com/assemble/generator-assemble. generators are far more powerful and flexible, so we can do everything you mentioned, it's just a matter of getting feedback and supporting them.
