### ISSUE TITLE
Why is bower still being used

### ISSUE THREAD

**Issue by AAllport** [ghost-town/grunt-init-assemble#16]
This is mostly a question, but why is bower still being used, would it not be better to install jquery and bootstrap with npm/yarn and adjust the paths in the build script accordingly?
I am happy to do the work myself if that is the restricting factor

**Comment by doowb** [comment]
@AAllport this project is in our `ghost-town` org meaning that it's essentially deprecated:

> The place where Assemble's deprecated projects go to wither away.

If you're using this project and would like to update it, feel free to do so. I'll add you as a collaborator too if you'd like.

**Comment by AAllport** [comment]
If it's deprecated then it's deprecated, just didn't realize. Dw
