### ISSUE TITLE
Custom Gruntfile.js build 

### ISSUE THREAD

**Issue by ajmalafif** [ghost-town/grunt-init-assemble#7]
Hey guys!

I'm stumbled upon assemble.io and from what I could absorb and understand, it's totally mind-blowing.

I'm fairly new to Javascript and the whole development tools like Grunt, Bower, Yeoman and what not.

I've tinker around with all the repos (bootstrap, gist, init-assemble etc.) and manage to edit some files and pick up few things with trial-and-error. 

However I still can't replicate the layout that I wanted with it (which is painful because from my understanding assemble should have no problem pulling it off).

Would you guys mind pointing me to the right direction and leave me some guides so I could at least have some progress with the layouts? 

I made a quick visualization of what I meant earlier below;

I think I got the first (index.html) but struggling with the second part which is doing the collections of posts & generating each post itself. Thanks a bunch! 

<img src="http://ajmalafif.s3.amazonaws.com/github/assemble.jpg" />

**Comment by hariadi** [comment]
grunt-init-assemble only generate standard Gruntfile.js for working with Assemble which you can customize.

Take a look at [this](http://assemble.io/docs/options-collections.html#pages-collection-differences) and [this](http://assemble.io/docs/Pages-Collections.html) documentation.

Also [sample](https://github.com/assemble/assemble/issues/363#issuecomment-26683839) Assemble config

**Comment by ajmalafif** [comment]
Thanks @hariadi looking into it now!

UPDATE: I actually went through few times already but can't wrap my head around it. Any suggestion like how I can see it from different angle? For now I'll just keep trying and playing around to see if I will learn/pickup anything.

**Comment by jonschlinkert** [comment]
@ajmalafif let me work on something to help you out with this. I was already going to publish a blog theme, this is related enough to that so I'll try to get something pushed up today.

@doowb I'll need your help getting the "page of pages" and "page of posts" working the way it should. I think this could (or maybe should) be done with helpers. The helper I think has the most potential for this is https://github.com/helpers/compose. But we'll need to do paging/pagination as well. 

a "page of pages" is probably the most-wanted feature atm.

**Comment by ajmalafif** [comment]
@jonschlinkert hey jon thanks so much! Sorry if it's too much of a trouble because it sounds like it's too much of a question (sorry can't help to peek at your message to doowb and sounds like the one I asked is actually page of pages/posts!). 

Thanks again! I'm still working it out myself though I'm playing around with default.hbs and home.hbs with boilerplate-bootstrap example. Nothing close to what I drew but it's a good learning experience so far. Maybe I should make like a blog post (like assemble.io from beginner point of view or something).

**Comment by dganoff** [comment]
This is exactly what I was trying to do today as well! I just started using assemble and thought it would be perfect for creating a portfolio/blog (practically the same structure that @ajmalafif is going for).

It would be incredibly helpful to see how to easily generate a list of pages from a posts directory. Thank you!

**Comment by jonschlinkert** [comment]
nice! good timing, we're actually still working on it right now. I'll update as soon as we have a working demo for you :-)

**Comment by dganoff** [comment]
@jonschlinkert Much appreciated!

**Comment by jonschlinkert** [comment]
Okay, this is just a start, @doowb and I still need to fix some jankiness in the pagination, but this works well enough to play around with it (IMO). Over the next couple of days we'll be improving the example to show multiple sections, and better paging:
- https://github.com/upstage/assemble-blog-theme
- http://upstage.github.io/assemble-blog-theme/index.html

If you have a chance to look at it, let me know what questions you have, and how you would make it better for new users. thanks!

**Comment by ajmalafif** [comment]
I just had time to finally try this. Will share any questions and let you guys know how it goes for me! 

Thanks again @jonschlinkert much appreciated!

**Comment by dganoff** [comment]
Thanks @jonschlinkert! I have a few questions after cloning your assemble-blog-theme repo...
1. For the blog posts, you are using the templates/index.hbs as the src file. This is confusing and I don't see how it gets used when the pages are created from pages.posts?
2. On the homepage, you have hard-coded a list of blog posts (excerpts). This was one of the things I wanted to automate from a list of posts inside their own directory.
   - For instance, if I have all my posts in: src/templates/blog/posts/*.hbs, I want to have a 'blogroll' page in the parent directory that loops through all the files in /posts/. The loop could grab YAML front matter data from each post for the excerpt information. Is this possible?
3. Could we use the permalinks plugin to create date URL paths? IE: www.domain.com/blog/2013/10/21/blog-title.html
   - This one might be more difficult, but it does seem to be a standard in blog permalink formatting.
4. Lastly, why did you choose to put the post content inside the pages.json file? It would seem to be easier to write the blog content inside its own .hbs or .md file, no?

Your help is very much appreciated!

Thanks!

**Comment by dganoff** [comment]
I actually just found this Assemble plugin ([assemble-related-pages](https://github.com/adjohnson916/assemble-related-pages)) that allows me to create my blogroll list I mentioned above. All I needed to do was put my blogroll page in the same directory as my blog post pages and add a YAML tag "blogs" to all the posts as well as my blogroll page. Then I could use the loop demonstrated on [this page](https://github.com/adjohnson916/assemble-related-pages/blob/master/example/1/src/layouts/default.hbs) to list out my posts.

This also allows me to use custom data from YAML to display things like published date, last updated, etc.

You can check out the project I applied this to (still working on it as we speak) here: https://github.com/dganoff/personal-site

Next, I might try adding the permalinks plugin to create better URL paths :).

EDIT: I just realized this method does not play well with the #withSort helper. Currently working on a way to sort these posts by the date listed in the YAML...

**Comment by ajmalafif** [comment]
hey @dganoff I thought they already have it here? https://github.com/assemble/permalinks

Is that what you're looking for?

Hmm I don't want to request any further because I actually feel bad after all those hassle it took you guys. So I'll try to reverse engineer and try it out myself (wish me luck) to assemble it. 

I found a site that works like what I drew earlier; So a page with a list of posts. Each post links to dedicated post (pagination is optional). 

And it's the same for blog part but it's using markdown as layout/format.

http://playgroundinc.com/work/

I would appreciate any guide or advice if it's something not (yet) doable with assemble, so I don't spend/waste too much time doing the impossible. I don't think any other framework comes close to creating this (of course I meant static generators).

**Comment by jonschlinkert** [comment]
@dganoff thanks for the detailed feedback! although premature since as I mentioned it's not finished. 

> I would appreciate any guide or advice if it's something not (yet) doable with assemble, so I don't spend/waste too much time doing the impossible. 

it's not easy yet, this is what we're working on now. 

> I don't want to request any further 

please do! we can't make assemble better unless we know what you want!

**Comment by ajmalafif** [comment]
@jonschlinkert thanks for the encouraging words!

Oh hm now that I read again my comment it sounded wrong. What I meant was it'll be great if any experts here could call out my noob attempt at never-ending silos :ocean: :frowning: 

So instead that way I could be productive and hopefully contribute in other way that I am able. 

And sorry for the confusion. In my head somehow when I see the demo and docs, I thought it's already doable. But anyways, I could think of some other projects to highlight the feature of the current blog theme you guys just made!

**Comment by jonschlinkert** [comment]
>  I thought it's already doable.

Well, everything that has been mentioned here is 100% doable currently, but like I mentioned _it's not easy_, and it would require some programming. 

no worries at all, please feel comfortable adding whatever feedback comes to mind!

**Comment by ajmalafif** [comment]
I was so curious (they said the best way to learn is to have a project) that I went on my diving-head first exploration on how to achieve what I illustrated on the first post. 

So from what I understand (please correct me if im wrong), I could use .hbs helpers (like the ones used in lorem.js and pager.js) to actually make assemble processed a specified list of posts in one page. 

I'm actually stuck to a point I don't know what files should be edited/worked on to process the {#each} helpers. It's far above my head, but I'm willing to tinker and experiment to make it work. I'm writing this to seek help with quick pointers in the guide & map so I could head to the right direction. Any help/idea @jonschlinkert @hariadi @doowb ?

Thanks guys! 

ps: I ended up exploring a lot about assemble and I have to say what you guys did are super awesome! Can't wait until I am capable of contributing and offer help :smile:

**Comment by hariadi** [comment]
Do you have working repo? We need to see your sample work/blog data (json/yaml/md)

From your first post, you need to add this files under `templates` folder

```
templates/
  - home.hbs
  - work.hbs
  - blog.hbs
```

this method requires permalink plugin (just use preset: pretty) which generate to:

```
dest/home/index.html
dest/work/index.html
dest/blog/index.html
```

## Method using data

So you need to edited/worked  `{#each}/ {#withSort}` helper on page above (.hbs) with your data

Sample work.json

``` json
[
    {
        "id": 1,
        "title": "W Network",
        "desc": "Description 1",
        "url": "http: //example.com/work/1"
    },
    {
        "id": 2,
        "title": "MagellanVacations",
        "desc": "Description 2",
        "url": "http: //example.com/work/2"
    },
    {
        "id": 3,
        "title": "CanadaGoose",
        "desc": "Description 3",
        "url": "http: //example.com/work/3"
    },
    {
        "id": 4,
        "title": "Suitly",
        "desc": "Description 4",
        "url": "http: //example.com/work/4"
    }
]
```

work.hbs

``` html
<article id="work-index" class="index">
    {{withSort work dir="desc"}}
    <article>
        <a href="{{{url}}}">
            <h1>{{title}}</h1>
            <p class="note">{{desc}}</p>
        </a>
    </article>
    {{#withSort}}
</article>
```

## Method using helper

Use special helpers like [{{aggregate}}](http://assemble.io/helpers/helper-aggregate.html) or [{{compose}}](http://assemble.io/helpers/helper-compose.html)

Clone [this repo](https://github.com/helpers/yfm) to see example templates and content.

Hope this can help you.

**Comment by ajmalafif** [comment]
@hariadi

Hey thanks for the detailed walkthrough. I didn't receive notification hmm thats weird. Sorry for the delayed response wasn't aware of the update. Just saw this as I was trying to share some progress.

Oh apparently I don't but I could make a quick fake one quickly. 

Seems like what you suggested could be it. Will report how is it working and share the result as well!

Thanks a bunch again!

**Comment by jonschlinkert** [comment]
We're also about to start refactoring, and I think this is a top priority for that...

**Comment by ajmalafif** [comment]
Okay maybe I'll just tinker around with it to get familiar.

It's safer for me to just wait for the refactoring rather than trying to
make my way through it.

Can't wait! Really want to publish this project with Assemble!
